{\rtf1\ansi\ansicpg1252\cocoartf2580
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 \
SELECT ("PACKAGE"), ("TERM"), ("DISC"), ("BILLING_METHOD") , sum("MER") AS "REVENUE"\
FROM\
  (SELECT "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."SBSCRN_ACTVTY_KEY" AS "SBSCRN_ACTVTY_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."SBSCRN_ID" AS "SBSCRN_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."ACTVTY_TYPE_ID" AS "ACTVTY_TYPE_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."USED_ACTVTY_TYPE_ID" AS "USED_ACTVTY_TYPE_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."ACTVTY_DT" AS "ACTVTY_DT",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."ACTVTY_TS" AS "ACTVTY_TS",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."HHLD_ID" AS "HHLD_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PRTY_KEY" AS "PRTY_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PRTY_ID" AS "PRTY_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PARNT_ACCT_KEY" AS "PARNT_ACCT_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PARNT_ACCT_ID" AS "PARNT_ACCT_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PARNT_ACCT_NUM" AS "PARNT_ACCT_NUM",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."CHILD_ACCT_KEY" AS "CHILD_ACCT_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."CHILD_ACCT_ID" AS "CHILD_ACCT_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."CHILD_ACCT_NUM" AS "CHILD_ACCT_NUM",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."VEH_KEY" AS "VEH_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."DVC_KEY" AS "DVC_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."DVC_ID" AS "DVC_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."EQMNT_KEY" AS "EQMNT_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."EQMNT_ID" AS "EQMNT_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PLAN_KEY" AS "PLAN_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PLAN_ID" AS "PLAN_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."OFR_ID" AS "OFR_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_PLAN_KEY" AS "FROM_PLAN_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_PLAN_ID" AS "FROM_PLAN_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_OFR_ID" AS "FROM_OFR_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PROD_KEY" AS "PROD_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PROD_ID" AS "PROD_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_PROD_KEY" AS "FROM_PROD_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_PROD_ID" AS "FROM_PROD_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PKG_ID" AS "PKG_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_PKG_ID" AS "FROM_PKG_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."FEAT_ID" AS "FEAT_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."AGN_KEY" AS "AGN_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."CSR_ID" AS "CSR_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PTNR_ID" AS "PTNR_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."LNKD_INET_FL" AS "LNKD_INET_FL",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."MRD_TYPE_CD" AS "MRD_TYPE_CD",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."SBSCR_LIFCYC_KEY" AS "SBSCR_LIFCYC_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."CONV_REP_OWN_SEGMT_KEY" AS "CONV_REP_OWN_SEGMT_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."OWNR_TYPE2_KEY" AS "OWNR_TYPE2_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."DEACTIVATION_REASON_CODE" AS "DEACTIVATION_REASON_CODE",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."TRIAL_ID" AS "TRIAL_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."SRVC_ID" AS "SRVC_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."RENW_ID" AS "RENW_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_RENW_ID" AS "FROM_RENW_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."COLL_SCNRO_ID" AS "COLL_SCNRO_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."SRVC_LVL_PMT_KEY" AS "SRVC_LVL_PMT_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."NONPAY_SRVC_KEY" AS "NONPAY_SRVC_KEY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."BILLING_METHOD" AS "BILLING_METHOD",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_BILLING_METHOD" AS "FROM_BILLING_METHOD",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."SLFPAY_TURNOVER_RSN" AS "SLFPAY_TURNOVER_RSN",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."SLFPAY_TURNOVER_DT" AS "SLFPAY_TURNOVER_DT",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."FUTURE_DEACTVN_DT" AS "FUTURE_DEACTVN_DT",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."SCHD_SEASONAL_SUSP_REACTVN_DT" AS "SCHD_SEASONAL_SUSP_REACTVN_DT",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."CALL_REASON" AS "CALL_REASON",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."CALL_DISPOSITION" AS "CALL_DISPOSITION",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."INSE_USER_ID" AS "INSE_USER_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."INSE_TS" AS "INSE_TS",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."UPDT_USER_ID" AS "UPDT_USER_ID",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."UPDT_TS" AS "UPDT_TS",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."SAVE_ACTIVITY" AS "SAVE_ACTIVITY",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."DEACT_ACTIVITY_BY_SAVE_AGENT" AS "DEACT_ACTIVITY_BY_SAVE_AGENT",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."CONVERSION_ACTIVITY_BY_SAVE_AGENT" AS "CONVERSION_ACTIVITY_BY_SAVE_AGENT",\
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."SAVE_OPPORTUNITY_ACTIVITY" AS "SAVE_OPPORTUNITY_ACTIVITY",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."PLAN_ID" AS "PLAN_ID2",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."PLAN_NAME" AS "PLAN_NAME",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."MER" AS "MER",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."DISC" AS "DISC",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."PACKAGE" AS "PACKAGE",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."LEN" AS "TERM",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."ROLLUP1" AS "ROLLUP1",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."ASP" AS "ASP",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."STARTDATE" AS "STARTDATE",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."ENDDATE" AS "ENDDATE",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_RECORD_KEY" AS "AGENT_RECORD_KEY",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_ID" AS "AGENT_ID",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."CSR_ID" AS "CSR_ID2",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_SUPERVISOR_RECORD_KEY" AS "AGENT_SUPERVISOR_RECORD_KEY",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_SUPERVISOR_CSR_ID" AS "AGENT_SUPERVISOR_CSR_ID",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_STATUS" AS "AGENT_STATUS",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_ROLE_START_DATE" AS "AGENT_ROLE_START_DATE",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_ROLE_END_DATE" AS "AGENT_ROLE_END_DATE",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_ROLE_SMS" AS "AGENT_ROLE_SMS",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_ROLE_MARKETING" AS "AGENT_ROLE_MARKETING",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_LOCATION" AS "AGENT_LOCATION",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_VENDOR" AS "AGENT_VENDOR",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_SITE" AS "AGENT_SITE",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_LOB" AS "AGENT_LOB",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."ACTIVATION_SOURCE" AS "ACTIVATION_SOURCE",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."CURRENT_RECORD_FLAG" AS "CURRENT_RECORD_FLAG",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."DELETED_RECORD_FLAG" AS "DELETED_RECORD_FLAG",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE"."REASONCODETYPE" AS "REASONCODETYPE",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE"."REASONCODE" AS "REASONCODE",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE"."REASONNAME" AS "REASONNAME",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE"."REACTIVATION_INTERVAL" AS "REACTIVATION_INTERVAL",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE"."TEMP_DEACTIVATION_IND" AS "TEMP_DEACTIVATION_IND",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE"."TEMP_DEACTIVATION_INTERVAL" AS "TEMP_DEACTIVATION_INTERVAL",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE"."REASONNAMEROLLUP" AS "REASONNAMEROLLUP",\
          "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE"."REASON_CODE_GROUP" AS "REASON_CODE_GROUP"\
   FROM "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"\
   LEFT OUTER JOIN "preview1_oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES" ON ("snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PLAN_ID" = "preview1_oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."PLAN_ID")\
   LEFT OUTER JOIN "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT" ON ("snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."AGN_KEY" = "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_AGENT"."AGENT_RECORD_KEY")\
   LEFT OUTER JOIN "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE" ON ("snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."CALL_REASON" = "preview1_oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE"."REASONCODE"))\
GROUP BY ("PACKAGE"),("TERM"),("DISC"),("BILLING_METHOD")\
LIMIT 10000}