WITH subscription_sales as (
  SELECT
    "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"."PLAN_KEY" AS "PLAN_KEY",
    "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"."PLAN_ID" AS "PLAN_ID",
    "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"."CALL_REASON" AS "CALL_REASON",
    "oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."PLAN_ID" AS "PLAN_ID2",
    "oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."PLAN_NAME" AS "PLAN_NAME",
    "oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."MER" AS "MER",
    "oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."PACKAGE" AS "PACKAGE",
    "oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE"."REASONNAME" AS "REASONNAME"
  FROM
    "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"
    LEFT OUTER JOIN "oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES" ON (
      "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"."PLAN_ID" = "oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."PLAN_ID"
    )
    LEFT OUTER JOIN "oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE" ON (
      "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"."CALL_REASON" = "oracle"."RDSORACLEFORPRESTO"."DIM_REASONCODE"."REASONCODE"
    )
)
SELECT
  ("REASONNAME") AS "reason",
  ("PLAN_NAME") AS "plan",
  ("PACKAGE") AS "promo package",
  sum("MER") AS "revenue"
from
  subscription_sales
GROUP BY
  ("REASONNAME"),("PLAN_NAME"),("PACKAGE")