SELECT ("PACKAGE") AS "PACKAGE",
       ("TERM") AS "CONTRACT TERM",
       ("DISC") AS "DISCOUNT",
       ("BILLING_METHOD") AS "BILLING METHOD",
       sum("MER") AS "REVENUE"
FROM
  (SELECT "oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."PACKAGE" AS "PACKAGE",
          "oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."LEN" AS "TERM",
          "oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."DISC" AS "DISC",
          "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."BILLING_METHOD" AS "BILLING_METHOD",
          "oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."MER" AS "MER"
   FROM "snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"
   LEFT OUTER JOIN "oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES" ON ("snowflake"."SCHEMA_INFO"."FACT_SUBSCRIPTION_ACTIVITY"."PLAN_ID" = "oracle"."RDSORACLEFORPRESTO"."MASTER_PLAN_TABLE_WDATES"."PLAN_ID"))
GROUP BY "PACKAGE",
         "TERM",
         "DISC",
         "BILLING_METHOD"
LIMIT 10000