SELECT OFFERING,
       OWNERSHIP,
       PLAN_DETAIL,
       sum("MER") AS REVENUE
FROM
  (SELECT "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"."PKG_ID" AS "OFFERING",
          "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"."MRD_TYPE_CD" AS "OWNERSHIP",
          "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"."BILLING_METHOD" AS "BILLING_METHOD",
          "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"."FROM_BILLING_METHOD" AS "FROM_BILLING_METHOD",
          "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"."CALL_REASON" AS "CALL_REASON",
          "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"."CALL_DISPOSITION" AS "CALL_DISPOSITION",
          "snowflake"."SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."PLAN_NAME" AS "PLAN_NAME",
          "snowflake"."SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."MER" AS "MER",
          "snowflake"."SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."DISC" AS "DISC",
          "snowflake"."SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."PACKAGE" AS "PACKAGE",
          "snowflake"."SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."LEN" AS "LEN",
          "snowflake"."SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."ROLLUP1" AS "PLAN_DETAIL"
   FROM "oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"
   LEFT OUTER JOIN "snowflake"."SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES" ON ("oracle"."RDSORACLEFORPRESTO"."FACT_SUBSCRIPTION_ACTIVITY"."PLAN_ID" = "snowflake"."SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"."PLAN_ID"))
GROUP BY OFFERING,
         OWNERSHIP,
         PLAN_DETAIL
LIMIT 1000